//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uch.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public string Code { get; set; }
        public string Number { get; set; }
    
        public virtual Specialization Specialization { get; set; }
    }
}
