//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uch.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries_Ishkeev
    {
        public string CountryName { get; set; }
        public string Capital { get; set; }
        public string Continent { get; set; }
        public int Population { get; set; }
        public double Area { get; set; }
        public Nullable<int> GovernanceTypeID { get; set; }
    }
}
