//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uch.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gymnasts
    {
        public int ID { get; set; }
        public string LastName { get; set; }
        public string Subject { get; set; }
        public string School { get; set; }
        public Nullable<double> Scores { get; set; }
    }
}
